# Generated by Django 5.2.4 on 2025-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
