# Generated by Django 5.2.4 on 2025-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone_book", "0002_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
